services:
  ihm:
    build:
      context: .
      dockerfile: docker/ihm/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./app/ihm/src:/var/www/src
      - ./app/ihm/.env:/var/www/src/.env:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - API_PLATS_URL=http://host.docker.internal:3003
      - API_MENUS_URL=http://host.docker.internal:3004
      - API_COMMANDES_URL=http://host.docker.internal:3005
